// Dream 100 Accountants · seed data
// Edit this file to add, remove or update firms. Commit and push to update the deployed app.
// Contact data (DM name, email) is intentionally left blank. Add it via the app UI (browser-local) so it never lives in the public repo.
//
// STAFF COUNTS are best-guess from public signals (website "about us", LinkedIn company page hints).
// Erica must verify staff count and identify the decision maker on LinkedIn before Touch 1.
// Tier is a research-pass estimate. Re-tier using the Tier Criteria sheet in the spreadsheet after verification.

window.DREAM100_SEED = [
  // =============================================================
  // ORIGINAL 20 (manual research)
  // =============================================================

  // ----- TIER A -----
  { tier: "A", firm: "inniAccounts",                 web: "https://www.inniaccounts.co.uk",        region: "Midlands",      city: "Derby",            staff: "30-50", niche: "Contractors, small Ltd companies",     stack: "Proprietary platform, cloud-first",        title: "Managing Director", owner: "Kevin", notes: "Tech-forward firm, custom client portal. Values systems." },
  { tier: "A", firm: "Mazuma Accountants",           web: "https://mazumamoney.co.uk",             region: "Wales",         city: "Newport",          staff: "30-50", niche: "Micro / small SMEs, subscription model", stack: "Xero, FreeAgent, in-house tech",         title: "Founder / MD",      owner: "Kevin", notes: "Subscription-pricing firm, productised. Culturally aligned." },
  { tier: "A", firm: "The Accountancy Partnership", web: "https://www.theaccountancy.co.uk",      region: "North West",    city: "Wirral",           staff: "40-50", niche: "Online SME, fixed-fee",                 stack: "Pandle (own tool), Xero, QBO",            title: "Director",          owner: "Kevin", notes: "In-house product-builders, will get the OD value prop." },
  { tier: "A", firm: "Crunch",                       web: "https://www.crunch.co.uk",              region: "South East",    city: "Brighton",         staff: "50+",   niche: "Freelancers, contractors, small Ltd",   stack: "Own platform, Xero integrations",        title: "CEO / Founder",     owner: "Kevin", notes: "Cap may be over 50 staff. Verify, possibly Tier B." },
  { tier: "A", firm: "Ad Valorem",                   web: "https://www.advaloremgroup.uk",         region: "South East",    city: "Milton Keynes",    staff: "40-50", niche: "SME, advisory-led, Xero Platinum",      stack: "Xero Platinum, Receipt Bank, Spotlight",  title: "Managing Partner",  owner: "Kevin", notes: "Award-winning Xero firm, advisory positioning." },
  { tier: "A", firm: "Tayabali Tomlin",              web: "https://www.tayabalitomlin.com",        region: "South West",    city: "Cheltenham",       staff: "10-20", niche: "Advisory-led, growth firms",            stack: "Xero, FUTRLI, advisory tech",             title: "Founder",           owner: "Kevin", notes: "Strong advisory brand, vocal on LinkedIn." },
  { tier: "A", firm: "Boffix",                       web: "https://www.boffix.com",                region: "West Midlands", city: "Wolverhampton",    staff: "10-20", niche: "SME, fixed-fee, modern",                stack: "Xero, QBO",                               title: "Founder",           owner: "Kevin", notes: "Modern brand, social-active." },
  { tier: "A", firm: "Hentons",                      web: "https://www.hentons.com",               region: "Yorkshire",     city: "Leeds",            staff: "40-50", niche: "SME, owner-managed businesses",         stack: "Xero, modern stack",                      title: "Managing Partner",  owner: "Kevin", notes: "Mid-sized firm with growth advisory focus." },

  // ----- TIER B -----
  { tier: "B", firm: "TaxAssist Accountants (HQ)",   web: "https://www.taxassist.co.uk",           region: "East",          city: "Norwich",          staff: "50+",   niche: "SME franchise network, HQ team",        stack: "Various franchisee stacks",               title: "Network Director",  owner: "Erica", notes: "Approach HQ for network-wide partnership." },
  { tier: "B", firm: "Whitings LLP",                 web: "https://www.whitingsllp.co.uk",         region: "East",          city: "Bury St Edmunds",  staff: "40-50", niche: "Owner-managed SMEs, agriculture",       stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Regional firm, modernising." },
  { tier: "B", firm: "Forrester Boyd",               web: "https://www.forrester-boyd.co.uk",      region: "Yorkshire",     city: "Grimsby",          staff: "50+",   niche: "SME, regional",                          stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Larger firm, verify staff count for tier." },
  { tier: "B", firm: "ETC Hartley",                  web: "https://www.etchartley.co.uk",          region: "North West",    city: "Bury",             staff: "10-20", niche: "SME, contractors",                       stack: "Xero",                                    title: "Director",          owner: "Erica", notes: "Smaller firm, modern." },
  { tier: "B", firm: "Numbers Game Accountants",     web: "https://www.numbersgameaccountants.com",region: "South East",    city: "London",           staff: "10-20", niche: "Creative SMEs, start-ups",              stack: "Xero, FreeAgent",                         title: "Director",          owner: "Erica", notes: "Niche, creative sector." },
  { tier: "B", firm: "Sleek UK",                     web: "https://sleek.com/uk",                  region: "South East",    city: "London",           staff: "30-50", niche: "Online incorporation + accounting",     stack: "Own platform, Xero",                      title: "UK MD",             owner: "Erica", notes: "Tech-led but verify staff in UK office." },
  { tier: "B", firm: "Ridgefield Consulting",        web: "https://www.ridgefieldconsulting.co.uk",region: "South East",    city: "Oxford",           staff: "10-20", niche: "Contractors, small businesses",         stack: "Xero, QBO",                               title: "Director",          owner: "Erica", notes: "Modern boutique firm." },
  { tier: "B", firm: "Williamson & Croft",           web: "https://williamsoncroft.co.uk",         region: "North West",    city: "Manchester",       staff: "20-30", niche: "Property, SME advisory",                 stack: "Xero",                                    title: "Managing Partner",  owner: "Erica", notes: "Property-focused. Strong angle for Kevin." },
  { tier: "B", firm: "Howlader & Co",                web: "https://www.howladerandco.com",         region: "London",        city: "London",           staff: "10-20", niche: "SME, owner-managed",                     stack: "Xero, modern",                            title: "Founding Partner",  owner: "Erica", notes: "Advisory-positioned." },

  // ----- TIER C -----
  { tier: "C", firm: "DJH Mitten Clarke",            web: "https://www.djhmittenclarke.co.uk",     region: "West Midlands", city: "Stoke",            staff: "50+",   niche: "SME, regional",                          stack: "Sage",                                    title: "Managing Partner",  owner: "Erica", notes: "Larger and more traditional, lower probability." },
  { tier: "C", firm: "Albert Goodman",               web: "https://www.albertgoodman.co.uk",       region: "South West",    city: "Taunton",          staff: "50+",   niche: "Rural, SME",                              stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Big firm. Possibly out of scope." },
  { tier: "C", firm: "Bishop Fleming",               web: "https://www.bishopfleming.co.uk",       region: "South West",    city: "Bristol",          staff: "50+",   niche: "Mid-market",                              stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Possibly out of ICP size. Verify before contacting." },

  // =============================================================
  // RESEARCH PASS · 44 candidates added via web search (May 2026)
  // All require Erica to verify staff size + decision maker before Touch 1.
  // Tier assignments are best-guess from public signals.
  // =============================================================

  // ----- Xero Platinum / modern -----
  { tier: "A", firm: "Harrisons Accountancy",        web: "https://harrisonsaccountancy.co.uk",        region: "East",          city: "Biggleswade",      staff: "10-30", niche: "Media, entertainment SMEs",         stack: "Xero Platinum",                          title: "Managing Partner",  owner: "Erica", notes: "Xero Platinum Feb 2026. Modern niche positioning." },
  { tier: "A", firm: "Spicer & Co",                  web: "https://www.spicerandco.co.uk",             region: "East",          city: "Dunstable",        staff: "10-30", niche: "Chartered, cloud-first SME",        stack: "Xero Platinum",                          title: "Managing Partner",  owner: "Erica", notes: "Xero Platinum March 2026. Visible cloud adoption story." },
  { tier: "A", firm: "Inform Accounting",            web: "https://www.informaccounting.co.uk",        region: "West Midlands", city: "Sutton Coldfield", staff: "10-30", niche: "SME, owner-managed",                stack: "Xero Platinum",                          title: "Managing Director", owner: "Erica", notes: "Only Sutton Coldfield Xero Platinum firm. Strong modernity signal." },
  { tier: "A", firm: "The Numbersmith",              web: "https://www.thenumbersmith.co.uk",          region: "UK-wide (online)", city: "Remote",        staff: "5-20",  niche: "Cloud-first SME, online",            stack: "Xero Platinum",                          title: "Founder",           owner: "Erica", notes: "Productised online firm. Likely good fit. Verify size." },
  { tier: "A", firm: "Ascentis LLP",                 web: "https://ascentisllp.co.uk",                 region: "South",         city: "Verify",           staff: "10-30", niche: "Trade, construction, ecommerce",     stack: "Xero Platinum (specialist status)",      title: "Partner",           owner: "Erica", notes: "Xero specialist for trade, retail, ecommerce, prof services. Multi-niche." },
  { tier: "B", firm: "SRC Accountancy Services",     web: "https://srcaccountants.co.uk",              region: "West Midlands", city: "Stourbridge",      staff: "5-20",  niche: "Payroll + SME",                       stack: "Xero Platinum",                          title: "Director",          owner: "Erica", notes: "Smaller payroll-led firm. Possibly Tier A on closer look." },
  { tier: "B", firm: "THP Chartered Accountants",    web: "https://www.thpca.co.uk",                   region: "London + East", city: "Multi-office",     staff: "50+",   niche: "SME, startups, owner-managed",      stack: "Xero Gold",                              title: "Managing Partner",  owner: "Erica", notes: "5 offices, 50 years. Top of London SME lists. Verify size." },

  // ----- Contractor specialists -----
  { tier: "A", firm: "SG Accounting",                web: "https://sg-accounting.co.uk",               region: "South East",    city: "Camberley",        staff: "10-30", niche: "Contractors, small business",        stack: "FreeAgent, Xero",                        title: "Founder",           owner: "Erica", notes: "Contractor specialist with personal service angle." },
  { tier: "A", firm: "Gorilla Accounting",           web: "https://gorillaaccounting.com",             region: "North West",    city: "Bolton",           staff: "20-50", niche: "Contractors, landlords, freelancers", stack: "FreeAgent",                              title: "Director",          owner: "Erica", notes: "Productised, multi-niche. Strong digital brand." },
  { tier: "A", firm: "Dolan Accountancy",            web: "https://www.dolanaccountancy.com",          region: "South West",    city: "Verify",           staff: "10-30", niche: "Contractors, IR35 specialists",      stack: "FreeAgent",                              title: "Founder",           owner: "Erica", notes: "Fixed £125+VAT/mo model. Subscription-style." },
  { tier: "B", firm: "Danbro",                       web: "https://www.danbro.co.uk",                  region: "North West",    city: "Lytham",           staff: "30-50", niche: "Contractors, IR35",                  stack: "Various",                                title: "Managing Director", owner: "Erica", notes: "Family-run, contractor focus." },
  { tier: "B", firm: "No Worries",                   web: "https://www.no-worries.co.uk",              region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Freelancers, limited companies",     stack: "Joy Pilot",                              title: "Director",          owner: "Erica", notes: "Since 2005. Fixed-fee, contractor-focused." },
  { tier: "C", firm: "PaperRocket Accounting",       web: "https://www.paperrocketaccounting.co.uk",   region: "UK-wide",       city: "Verify",           staff: "1-4",   niche: "Sole practitioner, contractors",     stack: "FreeAgent",                              title: "Founder",           owner: "Erica", notes: "Sarah Solo, single chartered accountant. Below 5-staff target." },

  // ----- Property specialists -----
  { tier: "A", firm: "AccountingPreneur",            web: "https://www.accountingpreneur.com",         region: "London",        city: "London",           staff: "10-30", niche: "Property + hospitality SME",         stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Multi-niche property + hospitality. Strong Kevin angle." },
  { tier: "A", firm: "Cutts & Co",                   web: "https://cuttsandco.co.uk",                  region: "North West",    city: "Manchester",       staff: "10-30", niche: "Property specialist, landlords",     stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "Manchester property specialist. Aligns with Kevin's portfolio." },
  { tier: "A", firm: "Provestor",                    web: "https://www.provestor.co.uk",               region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Property tax, landlords, SPVs",      stack: "Own platform",                           title: "Founder",           owner: "Erica", notes: "Productised property tax firm. Tech-led." },
  { tier: "B", firm: "UK Property Accountants",      web: "https://www.ukpropertyaccountants.co.uk",   region: "London",        city: "London",           staff: "20-50", niche: "Property tax, real estate",          stack: "Various",                                title: "Managing Partner",  owner: "Erica", notes: "Larger property specialist. Verify modernity." },
  { tier: "B", firm: "Heighten Accountants",         web: "https://heightenaccountants.co.uk",         region: "London",        city: "Verify",           staff: "10-30", niche: "Property investors, developers",     stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Property specialism, advisory tone." },
  { tier: "C", firm: "GM Professional Accountants",  web: "https://gmprofessionalaccountants.co.uk",   region: "London",        city: "London",           staff: "5-20",  niche: "Property, landlord returns",         stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "2,000+ landlord returns. Possibly more compliance-led." },

  // ----- E-commerce specialists -----
  { tier: "A", firm: "Ecommerce Accountants",        web: "https://www.ecommerceaccountants.co.uk",    region: "London",        city: "London",           staff: "10-30", niche: "Amazon, Shopify, DTC brands",        stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Award-winning, 500+ clients. Modern niche." },
  { tier: "A", firm: "Unicorn Accounting",           web: "https://unicornaccounting.co.uk",           region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Ecommerce: Amazon, Shopify, Etsy",   stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Specialist ecommerce, fast-growing. Modern brand." },
  { tier: "A", firm: "Your Ecommerce Accountant",    web: "https://yourecommerceaccountant.co.uk",     region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "B2C/B2B sellers, multi-platform",    stack: "Xero, A2X",                              title: "Director",          owner: "Erica", notes: "Modern niche, smaller firm. Likely strong fit." },
  { tier: "B", firm: "GoEcom",                       web: "https://goecom.co.uk",                      region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Amazon FBA, Shopify",                 stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Bookkeeping from £39/mo. Productised but small." },
  { tier: "B", firm: "MJ Support",                   web: "https://www.mjsupport.co.uk",               region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Amazon FBA, dropshippers, Shopify",  stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Ecommerce niche. Verify modernity." },
  { tier: "C", firm: "BTB Accountants",              web: "https://www.btbaccountants.co.uk",          region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Ecommerce, restaurants",             stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Multi-niche. Verify if SME-fit." },
  { tier: "C", firm: "E2E Accounting",               web: "https://e2eaccounting.co.uk",               region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Ecommerce-curated content firm",     stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Publishes ecommerce thought leadership. Verify firm size vs content brand." },

  // ----- Creative / digital agency specialists -----
  { tier: "A", firm: "Accountancy Cloud",            web: "https://accountancycloud.com",              region: "London",        city: "London",           staff: "20-50", niche: "Creative agencies, startups",        stack: "Xero, own platform",                     title: "CEO",               owner: "Erica", notes: "Productised, tech-led firm for agencies. Strong fit." },
  { tier: "A", firm: "BAND",                         web: "https://weareband.co.uk",                   region: "London",        city: "London",           staff: "10-30", niche: "Creative & digital agencies",        stack: "Xero, advisory tools",                   title: "Founder",           owner: "Erica", notes: "Agency-only firm. Advisory positioning. Modern brand." },
  { tier: "A", firm: "A&C Chartered Accountants",    web: "https://www.ac-accounts.co.uk",             region: "North West",    city: "Manchester",       staff: "10-30", niche: "Creative, design, marketing agencies", stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "30 years agency experience. Fixed-fee modern model." },
  { tier: "A", firm: "Square Mile",                  web: "https://wearesquaremile.com",               region: "London",        city: "London",           staff: "10-30", niche: "Digital agencies",                   stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Agency-focused boutique. Modern brand." },
  { tier: "B", firm: "Lanop Business & Tax Advisors",web: "https://lanop.co.uk",                       region: "London",        city: "London",           staff: "30-50", niche: "Creative + virtual FD, multi-niche", stack: "Cloud-first",                            title: "Founder",           owner: "Erica", notes: "Larger, multi-niche. Possibly stretched ICP." },
  { tier: "B", firm: "WallsMan Creative",            web: "https://creative.accountants",              region: "London",        city: "Kingston / London",staff: "10-30", niche: "Creative industry tax + R&D",        stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Creative industry tax + R&D specialist." },
  { tier: "B", firm: "Buttmiller",                   web: "https://buttmiller.co.uk",                  region: "Verify",        city: "Verify",           staff: "5-20",  niche: "Creative industries",                stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Specialist creative firm. Verify size." },

  // ----- Modern SME advisory -----
  { tier: "A", firm: "Rise Accounting",              web: "https://riseaccounting.co.uk",              region: "London",        city: "London",           staff: "10-30", niche: "Growth-focused founders, outsourced FD", stack: "Xero, advisory tech",                title: "Founder",           owner: "Erica", notes: "Advisory-first brand. Strong cultural fit." },
  { tier: "A", firm: "Scaleup Finance",              web: "https://scaleupfinance.com",                region: "UK-wide",       city: "London",           staff: "20-50", niche: "Startups, scaleups, CFO services",   stack: "Cloud + own tools",                      title: "UK MD",             owner: "Erica", notes: "Outsourced CFO for scaleups. Tech-led." },
  { tier: "A", firm: "Beany",                        web: "https://beany.com",                         region: "UK-wide",       city: "Verify",           staff: "20-50", niche: "SMEs, Xero-first, online",           stack: "Xero",                                   title: "UK lead",           owner: "Erica", notes: "Productised online accountant for SMEs. Modern." },

  // ----- Hospitality / restaurant -----
  { tier: "B", firm: "Fusion Accountants",           web: "https://www.fusionaccountants.co.uk",       region: "London",        city: "London",           staff: "10-30", niche: "Hospitality, restaurants, hotels",   stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Hospitality fixed-fee. Possibly Tier A on closer look." },
  { tier: "B", firm: "LJS Accounting Services",      web: "https://www.ljsaccountingservices.com",     region: "North West",    city: "Liverpool",        staff: "10-30", niche: "Hospitality + leisure SMEs",         stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Regional hospitality specialist." },
  { tier: "B", firm: "Wellden Turnbull",             web: "https://www.wtca.co.uk",                    region: "South East",    city: "Verify",           staff: "20-50", niche: "Hospitality industry",                stack: "Verify",                                 title: "Partner",           owner: "Erica", notes: "Years of hospitality experience." },
  { tier: "B", firm: "Alexander & Co",               web: "https://alexander.co.uk",                   region: "North West",    city: "Manchester",       staff: "30-50", niche: "Restaurants, hospitality",            stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "Restaurant niche across UK." },
  { tier: "C", firm: "Diamond Accounting",           web: "https://diamond-accounting.co.uk",          region: "South",         city: "Hampshire",        staff: "5-20",  niche: "Hospitality Hampshire",               stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Smaller regional hospitality firm." },

  // ----- Construction / CIS -----
  { tier: "B", firm: "TTCA",                         web: "https://ttca.co.uk",                        region: "Verify",        city: "Verify",           staff: "5-20",  niche: "CIS, construction industry",          stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "CIS specialist. Verify modernity + size." },
  { tier: "C", firm: "Pro-AccX",                     web: "https://pro-accx.co.uk",                    region: "UK-wide (remote)", city: "Remote",        staff: "5-20",  niche: "CIS contractors + subcontractors",   stack: "Cloud-based",                            title: "Director",          owner: "Erica", notes: "Remote CIS accountant. Niche only." },
  { tier: "C", firm: "Acumen AGC",                   web: "https://acumenagc.com",                     region: "London",        city: "London",           staff: "5-20",  niche: "CIS, contractors, subcontractors",    stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "London CIS specialist." },

  // =============================================================
  // RESEARCH PASS 2 · 36 candidates to complete the 100 (May 2026)
  // Erica must verify staff size and identify the decision maker on LinkedIn before Touch 1.
  // =============================================================

  // ----- Scottish (Edinburgh + Glasgow) -----
  { tier: "A", firm: "Sutherland Black",             web: "https://www.sutherlandblack.co.uk",         region: "Scotland",      city: "Edinburgh",        staff: "20-50", niche: "SME, cloud migration, multi-office",  stack: "Xero Gold",                              title: "Managing Partner",  owner: "Erica", notes: "Edinburgh, Livingston, Glasgow offices. Xero Gold. Modern cloud-led brand." },
  { tier: "A", firm: "Anlo",                         web: "https://www.anlofin.com",                   region: "Scotland",      city: "Edinburgh",        staff: "10-30", niche: "SME cloud, Edinburgh + Johannesburg",  stack: "Xero Gold + Payroll certified",          title: "Founder",           owner: "Erica", notes: "Productised cloud practice. International team, modern." },
  { tier: "B", firm: "Johnston Smillie (JSCA)",      web: "https://www.jsca.co.uk",                    region: "Scotland",      city: "Edinburgh",        staff: "20-50", niche: "SMEs, sole traders, startups",         stack: "Xero certified",                         title: "Managing Partner",  owner: "Erica", notes: "Edinburgh office, Xero-certified advisors. Covers Fife, Lothians, Borders, Glasgow." },
  { tier: "B", firm: "AH&Co Chartered Accountants",  web: "https://www.ah-ltd.co.uk",                  region: "Scotland",      city: "Edinburgh",        staff: "10-20", niche: "Edinburgh SMEs, Xero",                 stack: "Xero",                                   title: "Managing Director", owner: "Erica", notes: "Edinburgh Xero specialist. Boutique." },

  // ----- Northern Ireland (Belfast) -----
  { tier: "A", firm: "PGR Chartered Accountants",    web: "https://www.pgraccountants.com",            region: "Northern Ireland", city: "Belfast",       staff: "10-30", niche: "SMEs, sole traders, NI digital",       stack: "QuickBooks (Intuit NI strategic partner)", title: "Managing Partner", owner: "Erica", notes: "Selected by Intuit as exclusive Strategic Partner for NI. Digital-first." },
  { tier: "A", firm: "M.B. McGrady & Co",            web: "https://www.mbmcgrady.co.uk",               region: "Northern Ireland", city: "Belfast",       staff: "10-30", niche: "SMEs, multi-sector",                   stack: "Xero certified",                         title: "Managing Partner",  owner: "Erica", notes: "Xero-certified team. Retail, construction, farming." },
  { tier: "B", firm: "PGM Chartered Accountants",    web: "https://www.pgmaccountants.com",            region: "Northern Ireland", city: "Belfast",       staff: "10-30", niche: "Belfast SMEs",                          stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "Belfast Xero partner." },
  { tier: "C", firm: "Streets Belfast",              web: "https://www.streets.uk/our-offices/belfast", region: "Northern Ireland", city: "Belfast",       staff: "20-50", niche: "SMEs, owner-managed (Streets group)", stack: "Verify",                                 title: "Partner (Belfast)", owner: "Erica", notes: "Belfast office of Streets. Verify if HQ approach better." },

  // ----- Wales (rural / agriculture) -----
  { tier: "A", firm: "WBV Ltd",                      web: "https://www.wbv.co.uk",                     region: "Wales",         city: "Neath / Swansea",  staff: "20-50", niche: "Rural Wales SME + farming",            stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Chartered accountants with dedicated rural team. Local Wales angle." },
  { tier: "B", firm: "Ashmole and Co",               web: "https://www.ashmole.co.uk",                 region: "Wales",         city: "South / West Wales",staff: "30-50", niche: "South + West Wales SME",              stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Established 1897. Multiple offices across South/West Wales." },

  // ----- Dental + medical specialists -----
  { tier: "A", firm: "Samera Dental Accountants",    web: "https://samera.co.uk",                      region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Dental practices, 25+ years",          stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "Productised dental specialist. Modern brand, content-led." },
  { tier: "B", firm: "Robson Laidler Dental",        web: "https://www.robson-laidler.co.uk",          region: "Yorkshire",     city: "Newcastle",        staff: "30-50", niche: "Dental, North East specialist",       stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "North East dental specialist. Established firm." },
  { tier: "B", firm: "Hazlewoods (Dental)",          web: "https://www.hazlewoods.co.uk",              region: "South West",    city: "Cheltenham",       staff: "50+",   niche: "Dental 30+ years",                     stack: "Verify",                                 title: "Partner (Dental)",  owner: "Erica", notes: "Larger firm. Approach the dental partner specifically." },
  { tier: "C", firm: "Lovewell Blake (Dental)",      web: "https://www.lovewell-blake.co.uk",          region: "East",          city: "Norwich",          staff: "50+",   niche: "Dental, 700+ practices",               stack: "Verify",                                 title: "Partner (Dental)",  owner: "Erica", notes: "Likely Top 100 firm. Dental team only is the target." },

  // ----- SaaS / tech / R&D specialists -----
  { tier: "A", firm: "Barnes & Scott",               web: "https://www.barnesandscott.com",            region: "London",        city: "London (Shoreditch)",staff: "10-30", niche: "Tech, digital, fintech startups",     stack: "Xero, R&D, SEIS / Series A",             title: "Founder",           owner: "Erica", notes: "First ICAEW UK firm specialising only in tech/fintech. Founded 2012." },
  { tier: "A", firm: "Unicorn Accountants (Tech)",   web: "https://www.unicornaccountants.co.uk",      region: "London",        city: "London (Paddington)",staff: "10-30", niche: "Tech startups, R&D claims",           stack: "Xero, ICAEW + ACCA",                     title: "Founder",           owner: "Erica", notes: "Different firm from Unicorn Accounting (ecomm). Tech founder specialist." },
  { tier: "B", firm: "On The Go Accountants",        web: "https://www.onthegoaccountants.co.uk",      region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Tech startups + R&D claims",          stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "Tech-startup focused." },
  { tier: "B", firm: "RSBC Accountants",             web: "https://www.rsbc.uk",                       region: "London",        city: "London",           staff: "20-50", niche: "SaaS, IT, digital",                    stack: "Cloud, SaaS metrics",                    title: "Managing Partner",  owner: "Erica", notes: "SaaS-specialist. Tracks ARR, MRR, churn for clients." },
  { tier: "B", firm: "MAH Chartered Accountants",    web: "https://www.mah.uk.com",                    region: "London",        city: "London (Liverpool St)",staff: "10-30", niche: "Fintech, tech startups",            stack: "Cloud",                                  title: "Partner",           owner: "Erica", notes: "Fintech-positioned ICAEW firm." },

  // ----- Charity / not-for-profit -----
  { tier: "A", firm: "NfP Accountants Ltd",          web: "https://nfpaccountants.co.uk",              region: "London",        city: "London",           staff: "5-20",  niche: "Small charities (<£1.5m), social enterprises", stack: "Cloud",                          title: "Founder",           owner: "Erica", notes: "Productised niche: only works with charities under £1.5m. Strong fit." },
  { tier: "B", firm: "PEM Accountants",              web: "https://www.pem.co.uk",                     region: "East",          city: "Cambridge",        staff: "50+",   niche: "Charities, non-profits, SMEs",         stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Cambridge specialist. Verify size." },
  { tier: "B", firm: "Bryden Johnson",               web: "https://bryden-johnson.co.uk",              region: "South East",    city: "Croydon",          staff: "20-50", niche: "Charity + not-for-profit, SME",       stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Largest independent in Croydon. Charity specialist." },

  // ----- Agriculture / rural (UK) -----
  { tier: "B", firm: "Crowthers Chartered Accountants", web: "https://www.crowthers.co.uk",            region: "Midlands",      city: "Verify",           staff: "10-30", niche: "Farm + agricultural specialists",     stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Farm-specialist team. Boutique." },
  { tier: "B", firm: "Hall Livesey Brown",           web: "https://hallliveseybrown.co.uk",            region: "North West",    city: "Verify",           staff: "20-50", niche: "Agriculture + rural, 90 years",       stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "90+ years agricultural specialism." },
  { tier: "B", firm: "Westcotts",                    web: "https://westcotts.uk",                      region: "South West",    city: "Verify",           staff: "50+",   niche: "Agriculture + SME multi-office",      stack: "Verify",                                 title: "Partner (Agri)",    owner: "Erica", notes: "South West multi-office. Approach agri partner." },

  // ----- Sustainability / B Corp -----
  { tier: "A", firm: "Green & Moore",                web: "https://greenandmoore.co.uk",               region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Ethical, B Corps, purpose-driven",    stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "B Corp specialist. Niche brand, strong cultural fit." },
  { tier: "A", firm: "Plus Accounting",              web: "https://www.plusaccounting.co.uk",          region: "South East",    city: "Brighton",         staff: "20-50", niche: "B Corp certified, SME advisory",      stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "B Corp certified Brighton firm. Modern brand." },
  { tier: "B", firm: "Randall & Payne",              web: "https://www.randall-payne.co.uk",          region: "South West",    city: "Cheltenham",       staff: "50+",   niche: "B Corp, advisory, 146 years",         stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "B Corp certified. Larger firm (verify if Tier B holds)." },

  // ----- Fractional CFO / virtual FD -----
  { tier: "A", firm: "The Finance People",           web: "https://www.thefinancepeopleuk.com",        region: "UK-wide",       city: "Verify",           staff: "20-50", niche: "Fractional CFO for SMEs",              stack: "Cloud + bespoke",                        title: "Founder",           owner: "Erica", notes: "Self-described #1 Fractional CFO firm UK. Strong cultural alignment." },
  { tier: "B", firm: "Sanders Partnership",          web: "https://www.sanderspartnership.co.uk",      region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Virtual FD / fractional FD for SMEs",  stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "Embedded financial mentoring." },
  { tier: "B", firm: "Wright CFO",                   web: "https://wrightcfo.co.uk",                   region: "London",        city: "London",           staff: "10-30", niche: "Fractional CFO + financial controller",stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "London on-demand finance leadership." },

  // ----- Manufacturing / engineering -----
  { tier: "A", firm: "Friend & Grant",               web: "https://www.friendandgrant.co.uk",          region: "South East",    city: "Verify",           staff: "10-30", niche: "Engineering + manufacturing SMEs",     stack: "Cloud",                                  title: "Managing Partner",  owner: "Erica", notes: "Engineering / manufacturing SME niche." },
  { tier: "B", firm: "Champion Accountants",         web: "https://www.championgroup.co.uk",           region: "North West",    city: "Manchester",       staff: "20-50", niche: "Manufacturing + engineering",          stack: "Verify",                                 title: "Managing Partner",  owner: "Erica", notes: "Multi-sector but strong manufacturing arm." },
  { tier: "B", firm: "TC Group (West Midlands)",     web: "https://www.tc-group.com",                  region: "West Midlands", city: "Verify",           staff: "50+",   niche: "Manufacturing + engineering + creative", stack: "Verify",                                title: "Partner (WM)",      owner: "Erica", notes: "One-stop-shop. Approach West Midlands partner." },

  // ----- Modern SME / boutique generalists -----
  { tier: "A", firm: "Oldfield Advisory",            web: "https://www.oldfieldadvisory.com",          region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Owner-managed SME growth advisory",    stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "SME profit/growth advisory positioning." },
  { tier: "A", firm: "Plus Minus Chartered Accountants", web: "https://www.plusminus.co.uk",          region: "London",        city: "London (SE)",      staff: "5-20",  niche: "Boutique SME, direct partner access",  stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Boutique ICAEW practice, clients deal with qualified accountants directly." },
  { tier: "B", firm: "WIS Accountancy",              web: "https://wisaccountancy.co.uk",              region: "London",        city: "London",           staff: "10-30", niche: "Fintech, ecommerce multi-niche",       stack: "Cloud",                                  title: "Founder",           owner: "Erica", notes: "Fintech + ecommerce specialist." },

];
