// Dream 100 Accountants · seed data
// Edit this file to add, remove or update firms. Commit and push to update the deployed app.
// Contact data (DM name, email) is intentionally left blank. Add it via the app UI (browser-local) so it never lives in the public repo.

window.DREAM100_SEED = [
  // ===== TIER A =====
  { tier: "A", firm: "inniAccounts",                 web: "https://www.inniaccounts.co.uk",        region: "Midlands",      city: "Derby",            staff: "30-50", niche: "Contractors, small Ltd companies",     stack: "Proprietary platform, cloud-first",        title: "Managing Director", owner: "Kevin", notes: "Tech-forward firm, custom client portal. Values systems." },
  { tier: "A", firm: "Mazuma Accountants",           web: "https://mazumamoney.co.uk",             region: "Wales",         city: "Newport",          staff: "30-50", niche: "Micro / small SMEs, subscription model", stack: "Xero, FreeAgent, in-house tech",         title: "Founder / MD",      owner: "Kevin", notes: "Subscription-pricing firm, productised. Culturally aligned." },
  { tier: "A", firm: "The Accountancy Partnership", web: "https://www.theaccountancy.co.uk",      region: "North West",    city: "Wirral",           staff: "40-50", niche: "Online SME, fixed-fee",                 stack: "Pandle (own tool), Xero, QBO",            title: "Director",          owner: "Kevin", notes: "In-house product-builders, will get the OD value prop." },
  { tier: "A", firm: "Crunch",                       web: "https://www.crunch.co.uk",              region: "South East",    city: "Brighton",         staff: "50+",   niche: "Freelancers, contractors, small Ltd",   stack: "Own platform, Xero integrations",        title: "CEO / Founder",     owner: "Kevin", notes: "Cap may be over 50 staff. Verify, possibly Tier B." },
  { tier: "A", firm: "Ad Valorem",                   web: "https://www.advaloremgroup.uk",         region: "South East",    city: "Milton Keynes",    staff: "40-50", niche: "SME, advisory-led, Xero Platinum",      stack: "Xero Platinum, Receipt Bank, Spotlight",  title: "Managing Partner",  owner: "Kevin", notes: "Award-winning Xero firm, advisory positioning." },
  { tier: "A", firm: "Tayabali Tomlin",              web: "https://www.tayabalitomlin.com",        region: "South West",    city: "Cheltenham",       staff: "10-20", niche: "Advisory-led, growth firms",            stack: "Xero, FUTRLI, advisory tech",             title: "Founder",           owner: "Kevin", notes: "Strong advisory brand, vocal on LinkedIn." },
  { tier: "A", firm: "Boffix",                       web: "https://www.boffix.com",                region: "West Midlands", city: "Wolverhampton",    staff: "10-20", niche: "SME, fixed-fee, modern",                stack: "Xero, QBO",                               title: "Founder",           owner: "Kevin", notes: "Modern brand, social-active." },
  { tier: "A", firm: "Hentons",                      web: "https://www.hentons.com",               region: "Yorkshire",     city: "Leeds",            staff: "40-50", niche: "SME, owner-managed businesses",         stack: "Xero, modern stack",                      title: "Managing Partner",  owner: "Kevin", notes: "Mid-sized firm with growth advisory focus." },

  // ===== TIER B =====
  { tier: "B", firm: "TaxAssist Accountants (HQ)",   web: "https://www.taxassist.co.uk",           region: "East",          city: "Norwich",          staff: "50+",   niche: "SME franchise network, HQ team",        stack: "Various franchisee stacks",               title: "Network Director",  owner: "Erica", notes: "Approach HQ for network-wide partnership." },
  { tier: "B", firm: "Whitings LLP",                 web: "https://www.whitingsllp.co.uk",         region: "East",          city: "Bury St Edmunds",  staff: "40-50", niche: "Owner-managed SMEs, agriculture",       stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Regional firm, modernising." },
  { tier: "B", firm: "Forrester Boyd",               web: "https://www.forrester-boyd.co.uk",      region: "Yorkshire",     city: "Grimsby",          staff: "50+",   niche: "SME, regional",                          stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Larger firm, verify staff count for tier." },
  { tier: "B", firm: "ETC Hartley",                  web: "https://www.etchartley.co.uk",          region: "North West",    city: "Bury",             staff: "10-20", niche: "SME, contractors",                       stack: "Xero",                                    title: "Director",          owner: "Erica", notes: "Smaller firm, modern." },
  { tier: "B", firm: "Numbers Game Accountants",     web: "https://www.numbersgameaccountants.com",region: "South East",    city: "London",           staff: "10-20", niche: "Creative SMEs, start-ups",              stack: "Xero, FreeAgent",                         title: "Director",          owner: "Erica", notes: "Niche, creative sector." },
  { tier: "B", firm: "Sleek UK",                     web: "https://sleek.com/uk",                  region: "South East",    city: "London",           staff: "30-50", niche: "Online incorporation + accounting",     stack: "Own platform, Xero",                      title: "UK MD",             owner: "Erica", notes: "Tech-led but verify staff in UK office." },
  { tier: "B", firm: "Ridgefield Consulting",        web: "https://www.ridgefieldconsulting.co.uk",region: "South East",    city: "Oxford",           staff: "10-20", niche: "Contractors, small businesses",         stack: "Xero, QBO",                               title: "Director",          owner: "Erica", notes: "Modern boutique firm." },
  { tier: "B", firm: "Williamson & Croft",           web: "https://williamsoncroft.co.uk",         region: "North West",    city: "Manchester",       staff: "20-30", niche: "Property, SME advisory",                 stack: "Xero",                                    title: "Managing Partner",  owner: "Erica", notes: "Property-focused. Strong angle for Kevin." },
  { tier: "B", firm: "Howlader & Co",                web: "https://www.howladerandco.com",         region: "London",        city: "London",           staff: "10-20", niche: "SME, owner-managed",                     stack: "Xero, modern",                            title: "Founding Partner",  owner: "Erica", notes: "Advisory-positioned." },

  // ===== TIER C =====
  { tier: "C", firm: "DJH Mitten Clarke",            web: "https://www.djhmittenclarke.co.uk",     region: "West Midlands", city: "Stoke",            staff: "50+",   niche: "SME, regional",                          stack: "Sage",                                    title: "Managing Partner",  owner: "Erica", notes: "Larger and more traditional, lower probability." },
  { tier: "C", firm: "Albert Goodman",               web: "https://www.albertgoodman.co.uk",       region: "South West",    city: "Taunton",          staff: "50+",   niche: "Rural, SME",                              stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Big firm. Possibly out of scope." },
  { tier: "C", firm: "Bishop Fleming",               web: "https://www.bishopfleming.co.uk",       region: "South West",    city: "Bristol",          staff: "50+",   niche: "Mid-market",                              stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Possibly out of ICP size. Verify before contacting." },

  // ===== UNSCORED SLOTS (80 to source) =====
  // The remaining 80 firms are intentionally blank. Use the Sourcing Methodology in the Dream 100 spreadsheet to fill them in.
  // Add new entries above this line, following the same shape.
];
