// Dream 100 Accountants · seed data
// Edit this file to add, remove or update firms. Commit and push to update the deployed app.
// Contact data (DM name, email) is intentionally left blank. Add it via the app UI (browser-local) so it never lives in the public repo.
//
// STAFF COUNTS are best-guess from public signals (website "about us", LinkedIn company page hints).
// Erica must verify staff count and identify the decision maker on LinkedIn before Touch 1.
// Tier is a research-pass estimate. Re-tier using the Tier Criteria sheet in the spreadsheet after verification.

window.DREAM100_SEED = [
  // =============================================================
  // ORIGINAL 20 (manual research)
  // =============================================================

  // ----- TIER A -----
  { tier: "A", firm: "inniAccounts",                 web: "https://www.inniaccounts.co.uk",        region: "Midlands",      city: "Derby",            staff: "30-50", niche: "Contractors, small Ltd companies",     stack: "Proprietary platform, cloud-first",        title: "Managing Director", owner: "Kevin", notes: "Tech-forward firm, custom client portal. Values systems." },
  { tier: "A", firm: "Mazuma Accountants",           web: "https://mazumamoney.co.uk",             region: "Wales",         city: "Newport",          staff: "30-50", niche: "Micro / small SMEs, subscription model", stack: "Xero, FreeAgent, in-house tech",         title: "Founder / MD",      owner: "Kevin", notes: "Subscription-pricing firm, productised. Culturally aligned." },
  { tier: "A", firm: "The Accountancy Partnership", web: "https://www.theaccountancy.co.uk",      region: "North West",    city: "Wirral",           staff: "40-50", niche: "Online SME, fixed-fee",                 stack: "Pandle (own tool), Xero, QBO",            title: "Director",          owner: "Kevin", notes: "In-house product-builders, will get the OD value prop." },
  { tier: "A", firm: "Crunch",                       web: "https://www.crunch.co.uk",              region: "South East",    city: "Brighton",         staff: "50+",   niche: "Freelancers, contractors, small Ltd",   stack: "Own platform, Xero integrations",        title: "CEO / Founder",     owner: "Kevin", notes: "Cap may be over 50 staff. Verify, possibly Tier B." },
  { tier: "A", firm: "Ad Valorem",                   web: "https://www.advaloremgroup.uk",         region: "South East",    city: "Milton Keynes",    staff: "40-50", niche: "SME, advisory-led, Xero Platinum",      stack: "Xero Platinum, Receipt Bank, Spotlight",  title: "Managing Partner",  owner: "Kevin", notes: "Award-winning Xero firm, advisory positioning." },
  { tier: "A", firm: "Tayabali Tomlin",              web: "https://www.tayabalitomlin.com",        region: "South West",    city: "Cheltenham",       staff: "10-20", niche: "Advisory-led, growth firms",            stack: "Xero, FUTRLI, advisory tech",             title: "Founder",           owner: "Kevin", notes: "Strong advisory brand, vocal on LinkedIn." },
  { tier: "A", firm: "Boffix",                       web: "https://www.boffix.com",                region: "West Midlands", city: "Wolverhampton",    staff: "10-20", niche: "SME, fixed-fee, modern",                stack: "Xero, QBO",                               title: "Founder",           owner: "Kevin", notes: "Modern brand, social-active." },
  { tier: "A", firm: "Hentons",                      web: "https://www.hentons.com",               region: "Yorkshire",     city: "Leeds",            staff: "40-50", niche: "SME, owner-managed businesses",         stack: "Xero, modern stack",                      title: "Managing Partner",  owner: "Kevin", notes: "Mid-sized firm with growth advisory focus." },

  // ----- TIER B -----
  { tier: "B", firm: "TaxAssist Accountants (HQ)",   web: "https://www.taxassist.co.uk",           region: "East",          city: "Norwich",          staff: "50+",   niche: "SME franchise network, HQ team",        stack: "Various franchisee stacks",               title: "Network Director",  owner: "Erica", notes: "Approach HQ for network-wide partnership." },
  { tier: "B", firm: "Whitings LLP",                 web: "https://www.whitingsllp.co.uk",         region: "East",          city: "Bury St Edmunds",  staff: "40-50", niche: "Owner-managed SMEs, agriculture",       stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Regional firm, modernising." },
  { tier: "B", firm: "Forrester Boyd",               web: "https://www.forrester-boyd.co.uk",      region: "Yorkshire",     city: "Grimsby",          staff: "50+",   niche: "SME, regional",                          stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Larger firm, verify staff count for tier." },
  { tier: "B", firm: "ETC Hartley",                  web: "https://www.etchartley.co.uk",          region: "North West",    city: "Bury",             staff: "10-20", niche: "SME, contractors",                       stack: "Xero",                                    title: "Director",          owner: "Erica", notes: "Smaller firm, modern." },
  { tier: "B", firm: "Numbers Game Accountants",     web: "https://www.numbersgameaccountants.com",region: "South East",    city: "London",           staff: "10-20", niche: "Creative SMEs, start-ups",              stack: "Xero, FreeAgent",                         title: "Director",          owner: "Erica", notes: "Niche, creative sector." },
  { tier: "B", firm: "Sleek UK",                     web: "https://sleek.com/uk",                  region: "South East",    city: "London",           staff: "30-50", niche: "Online incorporation + accounting",     stack: "Own platform, Xero",                      title: "UK MD",             owner: "Erica", notes: "Tech-led but verify staff in UK office." },
  { tier: "B", firm: "Ridgefield Consulting",        web: "https://www.ridgefieldconsulting.co.uk",region: "South East",    city: "Oxford",           staff: "10-20", niche: "Contractors, small businesses",         stack: "Xero, QBO",                               title: "Director",          owner: "Erica", notes: "Modern boutique firm." },
  { tier: "B", firm: "Williamson & Croft",           web: "https://williamsoncroft.co.uk",         region: "North West",    city: "Manchester",       staff: "20-30", niche: "Property, SME advisory",                 stack: "Xero",                                    title: "Managing Partner",  owner: "Erica", notes: "Property-focused. Strong angle for Kevin." },
  { tier: "B", firm: "Howlader & Co",                web: "https://www.howladerandco.com",         region: "London",        city: "London",           staff: "10-20", niche: "SME, owner-managed",                     stack: "Xero, modern",                            title: "Founding Partner",  owner: "Erica", notes: "Advisory-positioned." },

  // ----- TIER C -----
  { tier: "C", firm: "DJH Mitten Clarke",            web: "https://www.djhmittenclarke.co.uk",     region: "West Midlands", city: "Stoke",            staff: "50+",   niche: "SME, regional",                          stack: "Sage",                                    title: "Managing Partner",  owner: "Erica", notes: "Larger and more traditional, lower probability." },
  { tier: "C", firm: "Albert Goodman",               web: "https://www.albertgoodman.co.uk",       region: "South West",    city: "Taunton",          staff: "50+",   niche: "Rural, SME",                              stack: "Xero, Sage",                              title: "Managing Partner",  owner: "Erica", notes: "Big firm. Possibly out of scope." },
  { tier: "C", firm: "Bishop Fleming",               web: "https://www.bishopfleming.co.uk",       region: "South West",    city: "Bristol",          staff: "50+",   niche: "Mid-market",                              stack: "Sage, Xero",                              title: "Managing Partner",  owner: "Erica", notes: "Possibly out of ICP size. Verify before contacting." },

  // =============================================================
  // RESEARCH PASS · 44 candidates added via web search (May 2026)
  // All require Erica to verify staff size + decision maker before Touch 1.
  // Tier assignments are best-guess from public signals.
  // =============================================================

  // ----- Xero Platinum / modern -----
  { tier: "A", firm: "Harrisons Accountancy",        web: "https://harrisonsaccountancy.co.uk",        region: "East",          city: "Biggleswade",      staff: "10-30", niche: "Media, entertainment SMEs",         stack: "Xero Platinum",                          title: "Managing Partner",  owner: "Erica", notes: "Xero Platinum Feb 2026. Modern niche positioning." },
  { tier: "A", firm: "Spicer & Co",                  web: "https://www.spicerandco.co.uk",             region: "East",          city: "Dunstable",        staff: "10-30", niche: "Chartered, cloud-first SME",        stack: "Xero Platinum",                          title: "Managing Partner",  owner: "Erica", notes: "Xero Platinum March 2026. Visible cloud adoption story." },
  { tier: "A", firm: "Inform Accounting",            web: "https://www.informaccounting.co.uk",        region: "West Midlands", city: "Sutton Coldfield", staff: "10-30", niche: "SME, owner-managed",                stack: "Xero Platinum",                          title: "Managing Director", owner: "Erica", notes: "Only Sutton Coldfield Xero Platinum firm. Strong modernity signal." },
  { tier: "A", firm: "The Numbersmith",              web: "https://www.thenumbersmith.co.uk",          region: "UK-wide (online)", city: "Remote",        staff: "5-20",  niche: "Cloud-first SME, online",            stack: "Xero Platinum",                          title: "Founder",           owner: "Erica", notes: "Productised online firm. Likely good fit. Verify size." },
  { tier: "A", firm: "Ascentis LLP",                 web: "https://ascentisllp.co.uk",                 region: "South",         city: "Verify",           staff: "10-30", niche: "Trade, construction, ecommerce",     stack: "Xero Platinum (specialist status)",      title: "Partner",           owner: "Erica", notes: "Xero specialist for trade, retail, ecommerce, prof services. Multi-niche." },
  { tier: "B", firm: "SRC Accountancy Services",     web: "https://srcaccountants.co.uk",              region: "West Midlands", city: "Stourbridge",      staff: "5-20",  niche: "Payroll + SME",                       stack: "Xero Platinum",                          title: "Director",          owner: "Erica", notes: "Smaller payroll-led firm. Possibly Tier A on closer look." },
  { tier: "B", firm: "THP Chartered Accountants",    web: "https://www.thpca.co.uk",                   region: "London + East", city: "Multi-office",     staff: "50+",   niche: "SME, startups, owner-managed",      stack: "Xero Gold",                              title: "Managing Partner",  owner: "Erica", notes: "5 offices, 50 years. Top of London SME lists. Verify size." },

  // ----- Contractor specialists -----
  { tier: "A", firm: "SG Accounting",                web: "https://sg-accounting.co.uk",               region: "South East",    city: "Camberley",        staff: "10-30", niche: "Contractors, small business",        stack: "FreeAgent, Xero",                        title: "Founder",           owner: "Erica", notes: "Contractor specialist with personal service angle." },
  { tier: "A", firm: "Gorilla Accounting",           web: "https://gorillaaccounting.com",             region: "North West",    city: "Bolton",           staff: "20-50", niche: "Contractors, landlords, freelancers", stack: "FreeAgent",                              title: "Director",          owner: "Erica", notes: "Productised, multi-niche. Strong digital brand." },
  { tier: "A", firm: "Dolan Accountancy",            web: "https://www.dolanaccountancy.com",          region: "South West",    city: "Verify",           staff: "10-30", niche: "Contractors, IR35 specialists",      stack: "FreeAgent",                              title: "Founder",           owner: "Erica", notes: "Fixed £125+VAT/mo model. Subscription-style." },
  { tier: "B", firm: "Danbro",                       web: "https://www.danbro.co.uk",                  region: "North West",    city: "Lytham",           staff: "30-50", niche: "Contractors, IR35",                  stack: "Various",                                title: "Managing Director", owner: "Erica", notes: "Family-run, contractor focus." },
  { tier: "B", firm: "No Worries",                   web: "https://www.no-worries.co.uk",              region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Freelancers, limited companies",     stack: "Joy Pilot",                              title: "Director",          owner: "Erica", notes: "Since 2005. Fixed-fee, contractor-focused." },
  { tier: "C", firm: "PaperRocket Accounting",       web: "https://www.paperrocketaccounting.co.uk",   region: "UK-wide",       city: "Verify",           staff: "1-4",   niche: "Sole practitioner, contractors",     stack: "FreeAgent",                              title: "Founder",           owner: "Erica", notes: "Sarah Solo, single chartered accountant. Below 5-staff target." },

  // ----- Property specialists -----
  { tier: "A", firm: "AccountingPreneur",            web: "https://www.accountingpreneur.com",         region: "London",        city: "London",           staff: "10-30", niche: "Property + hospitality SME",         stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Multi-niche property + hospitality. Strong Kevin angle." },
  { tier: "A", firm: "Cutts & Co",                   web: "https://cuttsandco.co.uk",                  region: "North West",    city: "Manchester",       staff: "10-30", niche: "Property specialist, landlords",     stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "Manchester property specialist. Aligns with Kevin's portfolio." },
  { tier: "A", firm: "Provestor",                    web: "https://www.provestor.co.uk",               region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Property tax, landlords, SPVs",      stack: "Own platform",                           title: "Founder",           owner: "Erica", notes: "Productised property tax firm. Tech-led." },
  { tier: "B", firm: "UK Property Accountants",      web: "https://www.ukpropertyaccountants.co.uk",   region: "London",        city: "London",           staff: "20-50", niche: "Property tax, real estate",          stack: "Various",                                title: "Managing Partner",  owner: "Erica", notes: "Larger property specialist. Verify modernity." },
  { tier: "B", firm: "Heighten Accountants",         web: "https://heightenaccountants.co.uk",         region: "London",        city: "Verify",           staff: "10-30", niche: "Property investors, developers",     stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Property specialism, advisory tone." },
  { tier: "C", firm: "GM Professional Accountants",  web: "https://gmprofessionalaccountants.co.uk",   region: "London",        city: "London",           staff: "5-20",  niche: "Property, landlord returns",         stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "2,000+ landlord returns. Possibly more compliance-led." },

  // ----- E-commerce specialists -----
  { tier: "A", firm: "Ecommerce Accountants",        web: "https://www.ecommerceaccountants.co.uk",    region: "London",        city: "London",           staff: "10-30", niche: "Amazon, Shopify, DTC brands",        stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Award-winning, 500+ clients. Modern niche." },
  { tier: "A", firm: "Unicorn Accounting",           web: "https://unicornaccounting.co.uk",           region: "UK-wide",       city: "Verify",           staff: "10-30", niche: "Ecommerce: Amazon, Shopify, Etsy",   stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Specialist ecommerce, fast-growing. Modern brand." },
  { tier: "A", firm: "Your Ecommerce Accountant",    web: "https://yourecommerceaccountant.co.uk",     region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "B2C/B2B sellers, multi-platform",    stack: "Xero, A2X",                              title: "Director",          owner: "Erica", notes: "Modern niche, smaller firm. Likely strong fit." },
  { tier: "B", firm: "GoEcom",                       web: "https://goecom.co.uk",                      region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Amazon FBA, Shopify",                 stack: "Xero, A2X",                              title: "Founder",           owner: "Erica", notes: "Bookkeeping from £39/mo. Productised but small." },
  { tier: "B", firm: "MJ Support",                   web: "https://www.mjsupport.co.uk",               region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Amazon FBA, dropshippers, Shopify",  stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Ecommerce niche. Verify modernity." },
  { tier: "C", firm: "BTB Accountants",              web: "https://www.btbaccountants.co.uk",          region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Ecommerce, restaurants",             stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Multi-niche. Verify if SME-fit." },
  { tier: "C", firm: "E2E Accounting",               web: "https://e2eaccounting.co.uk",               region: "UK-wide",       city: "Verify",           staff: "5-20",  niche: "Ecommerce-curated content firm",     stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Publishes ecommerce thought leadership. Verify firm size vs content brand." },

  // ----- Creative / digital agency specialists -----
  { tier: "A", firm: "Accountancy Cloud",            web: "https://accountancycloud.com",              region: "London",        city: "London",           staff: "20-50", niche: "Creative agencies, startups",        stack: "Xero, own platform",                     title: "CEO",               owner: "Erica", notes: "Productised, tech-led firm for agencies. Strong fit." },
  { tier: "A", firm: "BAND",                         web: "https://weareband.co.uk",                   region: "London",        city: "London",           staff: "10-30", niche: "Creative & digital agencies",        stack: "Xero, advisory tools",                   title: "Founder",           owner: "Erica", notes: "Agency-only firm. Advisory positioning. Modern brand." },
  { tier: "A", firm: "A&C Chartered Accountants",    web: "https://www.ac-accounts.co.uk",             region: "North West",    city: "Manchester",       staff: "10-30", niche: "Creative, design, marketing agencies", stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "30 years agency experience. Fixed-fee modern model." },
  { tier: "A", firm: "Square Mile",                  web: "https://wearesquaremile.com",               region: "London",        city: "London",           staff: "10-30", niche: "Digital agencies",                   stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Agency-focused boutique. Modern brand." },
  { tier: "B", firm: "Lanop Business & Tax Advisors",web: "https://lanop.co.uk",                       region: "London",        city: "London",           staff: "30-50", niche: "Creative + virtual FD, multi-niche", stack: "Cloud-first",                            title: "Founder",           owner: "Erica", notes: "Larger, multi-niche. Possibly stretched ICP." },
  { tier: "B", firm: "WallsMan Creative",            web: "https://creative.accountants",              region: "London",        city: "Kingston / London",staff: "10-30", niche: "Creative industry tax + R&D",        stack: "Xero",                                   title: "Founder",           owner: "Erica", notes: "Creative industry tax + R&D specialist." },
  { tier: "B", firm: "Buttmiller",                   web: "https://buttmiller.co.uk",                  region: "Verify",        city: "Verify",           staff: "5-20",  niche: "Creative industries",                stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Specialist creative firm. Verify size." },

  // ----- Modern SME advisory -----
  { tier: "A", firm: "Rise Accounting",              web: "https://riseaccounting.co.uk",              region: "London",        city: "London",           staff: "10-30", niche: "Growth-focused founders, outsourced FD", stack: "Xero, advisory tech",                title: "Founder",           owner: "Erica", notes: "Advisory-first brand. Strong cultural fit." },
  { tier: "A", firm: "Scaleup Finance",              web: "https://scaleupfinance.com",                region: "UK-wide",       city: "London",           staff: "20-50", niche: "Startups, scaleups, CFO services",   stack: "Cloud + own tools",                      title: "UK MD",             owner: "Erica", notes: "Outsourced CFO for scaleups. Tech-led." },
  { tier: "A", firm: "Beany",                        web: "https://beany.com",                         region: "UK-wide",       city: "Verify",           staff: "20-50", niche: "SMEs, Xero-first, online",           stack: "Xero",                                   title: "UK lead",           owner: "Erica", notes: "Productised online accountant for SMEs. Modern." },

  // ----- Hospitality / restaurant -----
  { tier: "B", firm: "Fusion Accountants",           web: "https://www.fusionaccountants.co.uk",       region: "London",        city: "London",           staff: "10-30", niche: "Hospitality, restaurants, hotels",   stack: "Xero",                                   title: "Director",          owner: "Erica", notes: "Hospitality fixed-fee. Possibly Tier A on closer look." },
  { tier: "B", firm: "LJS Accounting Services",      web: "https://www.ljsaccountingservices.com",     region: "North West",    city: "Liverpool",        staff: "10-30", niche: "Hospitality + leisure SMEs",         stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Regional hospitality specialist." },
  { tier: "B", firm: "Wellden Turnbull",             web: "https://www.wtca.co.uk",                    region: "South East",    city: "Verify",           staff: "20-50", niche: "Hospitality industry",                stack: "Verify",                                 title: "Partner",           owner: "Erica", notes: "Years of hospitality experience." },
  { tier: "B", firm: "Alexander & Co",               web: "https://alexander.co.uk",                   region: "North West",    city: "Manchester",       staff: "30-50", niche: "Restaurants, hospitality",            stack: "Xero",                                   title: "Managing Partner",  owner: "Erica", notes: "Restaurant niche across UK." },
  { tier: "C", firm: "Diamond Accounting",           web: "https://diamond-accounting.co.uk",          region: "South",         city: "Hampshire",        staff: "5-20",  niche: "Hospitality Hampshire",               stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "Smaller regional hospitality firm." },

  // ----- Construction / CIS -----
  { tier: "B", firm: "TTCA",                         web: "https://ttca.co.uk",                        region: "Verify",        city: "Verify",           staff: "5-20",  niche: "CIS, construction industry",          stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "CIS specialist. Verify modernity + size." },
  { tier: "C", firm: "Pro-AccX",                     web: "https://pro-accx.co.uk",                    region: "UK-wide (remote)", city: "Remote",        staff: "5-20",  niche: "CIS contractors + subcontractors",   stack: "Cloud-based",                            title: "Director",          owner: "Erica", notes: "Remote CIS accountant. Niche only." },
  { tier: "C", firm: "Acumen AGC",                   web: "https://acumenagc.com",                     region: "London",        city: "London",           staff: "5-20",  niche: "CIS, contractors, subcontractors",    stack: "Verify",                                 title: "Director",          owner: "Erica", notes: "London CIS specialist." },

  // =============================================================
  // 36 SLOTS STILL TO SOURCE
  // Use the Sourcing Methodology sheet in the Dream100_Accountants.xlsx
  // Best routes from here:
  //   1. Warm intros from your network (highest converting)
  //   2. Xero Platinum/Gold directory (xero.com/uk/partners)
  //   3. LinkedIn Sales Navigator filtered by 5-50 headcount + UK + Accounting
  //   4. ICAEW Firm Find (find.icaew.com)
  // =============================================================
];
